name: JavaTwitchAPI 11

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B package
      - name: Rename artifacts
        run: mv target/JavaTwitchAPI-*-shaded.jar target/jta.jar
      - name: Archive artifacts
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: JavaTwitchAPI (JTA)
          path: target/jta.jar
